fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    limits: "#{source_dir}"
